server:
  servlet:
    context-path: /inventory/api/rpt
  port: 7071
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:6543/inventory-db'
    username: my_user
    password: my_password
    driverClassName: org.postgresql.Driver
connection:
  pool:
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 20
    maxIdleTime: 3000
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  packagesToScan: org.task.mint
kafka:
  boot:
    server: localhost:9091
  topic:
    name: inventory-topic
  consumer:
    group:
      id: inventory-group-id